server:
  port: 8080

spring:
  application:
    name: erp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: erp-dev
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: erp-dev
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: erp-gateway.yml
            group: DEFAULT_GROUP
            refresh: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 订单服务路由
        - id: order-service
          uri: lb://erp-order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2

        # 平台API服务路由
        - id: platform-service
          uri: lb://erp-platform-service
          predicates:
            - Path=/api/platform/**
          filters:
            - StripPrefix=2

    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
